export default [
  {
    _id: "A101",
    title: "Propulsion Assignment",
    description: "Assignment description",
    points: "100",
    dueDate: "2024-03-01",
    availableFromDate: "2024-02-01",
    availableUntilDate: "2024-04-01",
    course: "FS101",
  },
  {
    _id: "A102",
    title: "Combustion Analysis",
    description: "Assignment description",
    points: "100",
    dueDate: "2024-03-01",
    availableFromDate: "2024-02-01",
    availableUntilDate: "2024-04-01",
    course: "FS101",
  },
  {
    _id: "A103",
    title: "Nozzle Design Project",
    description: "Assignment description",
    points: "100",
    dueDate: "2024-03-01",
    availableFromDate: "2024-02-01",
    availableUntilDate: "2024-04-01",
    course: "FS101",
  },
  {
    _id: "A201",
    title: "Aerodynamics Quiz",
    description: "Assignment description",
    points: "100",
    dueDate: "2024-03-01",
    availableFromDate: "2024-02-01",
    availableUntilDate: "2024-04-01",
    course: "FS201",
  },
  {
    _id: "A202",
    title: "Flow Analysis",
    description: "Assignment description",
    course: "FS102",
  },
  {
    _id: "A203",
    title: "Heating Analysis",
    description: "Assignment description",
    course: "FS102",
  },
  {
    _id: "A301",
    title: "Structural Design Task",
    description: "Assignment description",
    course: "FS103",
  },
  {
    _id: "A302",
    title: "Orbital Calculations",
    description: "Assignment description",
    course: "FS103",
  },
  {
    _id: "A303",
    title: "Systems Engineering Exam",
    description: "Assignment description",
    course: "FS103",
  },
];
